### ISSUE TITLE
errors in compilation

### ISSUE THREAD

**Issue by disheng222** [BoxLib-Codes/Nyx#15]
I tried installing the Nyx with AMREX, but encountered a compilation error. 
My operations are shown as follows: 
1. I download amrex from github and install it by "./configure --prefix=/home/user/amrex-install;make;make install"
2. I then download Nyx, and cd Nyx/Exec/LyA. Modify GNUmakefile as follows: 
AMREX_HOME= [downloading pacakge] (instead of /home/user/amrex-install).
COMP    = gnu
3. Then, make. But I got the following errors: 
../../Source/NyxParticles.cpp: In member function ‘virtual void Nyx::init_particles()’:
../../Source/NyxParticles.cpp:396:59: error: no matching function for call to ‘DarkMatterParticleContainer::InitRandom(long int&, int&, Real&, bool&)’
                              particle_initrandom_serialize);

According to the user guide, I need to set the environmental variable AMREX_HOME, and I already did it.
export AMREX_HOME=/home/user/amrex-install

Any ideas? thanks!
Best,
Sheng

**Comment by WeiqunZhang** [comment]
For Nyx, you don't need to do step 1.  Just set `AMREX_HOME` to the amrex directory.

**Comment by disheng222** [comment]
I changed the AMREX_HOME as follows, but the same error appeared. 
[sdi@sdihost LyA]$ echo $AMREX_HOME
/home/sdi/Development/NYX/AMREX/amrex

../../Source/NyxParticles.cpp:396:59: error: no matching function for call to ‘DarkMatterParticleContainer::InitRandom(long int&, int&, Real&, bool&)’
                              particle_initrandom_serialize);
                                                           ^
In file included from /home/sdi/Development/NYX/AMREX/amrex/Src/Particle/AMReX_Particles.H:946:0,
                 from /home/sdi/Development/NYX/AMREX/amrex/Src/AmrCore/AMReX_AmrParticles.H:4,
                 from ../../Source/NyxParticleContainer.H:7,
                 from ../../Source/Nyx.H:10,
                 from ../../Source/NyxParticles.cpp:2:
/home/sdi/Development/NYX/AMREX/amrex/Src/Particle/AMReX_ParticleInit.H:769:1: note: candidate: void amrex::ParticleContainer<NStructReal, NStructInt, NArrayReal, NArrayInt>::InitRandom(long int, long unsigned int, const ParticleInitData&, bool, amrex::RealBox) [with int NStructReal = 4; int NStructInt = 0; int NArrayReal = 0; int NArrayInt = 0; amrex::ParticleContainer<NStructReal, NStructInt, NArrayReal, NArrayInt>::ParticleInitData = amrex::ParticleInitType<4, 0, 0, 0>]
 ParticleContainer<NStructReal, NStructInt, NArrayReal, NArrayInt>::
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sdi/Development/NYX/AMREX/amrex/Src/Particle/AMReX_ParticleInit.H:769:1: note:   no known conversion for argument 3 from ‘Real {aka double}’ to ‘const ParticleInitData& {aka const amrex::ParticleInitType<4, 0, 0, 0>&}’
../../Source/NyxParticles.cpp:422:47: error: no matching function for call to ‘DarkMatterParticleContainer::InitRandomPerBox(long int&, int&, Real&, amrex::MultiFab&)’
                                    particle_mf);
                                               ^
In file included from /home/sdi/Development/NYX/AMREX/amrex/Src/Particle/AMReX_Particles.H:946:0,
                 from /home/sdi/Development/NYX/AMREX/amrex/Src/AmrCore/AMReX_AmrParticles.H:4,
                 from ../../Source/NyxParticleContainer.H:7,
                 from ../../Source/Nyx.H:10,
                 from ../../Source/NyxParticles.cpp:2:
/home/sdi/Development/NYX/AMREX/amrex/Src/Particle/AMReX_ParticleInit.H:964:1: note: candidate: void amrex::ParticleContainer<NStructReal, NStructInt, NArrayReal, NArrayInt>::InitRandomPerBox(long int, long unsigned int, const ParticleInitData&) [with int NStructReal = 4; int NStructInt = 0; int NArrayReal = 0; int NArrayInt = 0; amrex::ParticleContainer<NStructReal, NStructInt, NArrayReal, NArrayInt>::ParticleInitData = amrex::ParticleInitType<4, 0, 0, 0>]
 ParticleContainer<NStructReal, NStructInt, NArrayReal, NArrayInt>
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sdi/Development/NYX/AMREX/amrex/Src/Particle/AMReX_ParticleInit.H:964:1: note:   candidate expects 3 arguments, 4 provided
/home/sdi/Development/NYX/AMREX/amrex/Tools/GNUMake/Make.rules:134: recipe for target 'tmp_build_dir/o/3d.gnu.MPI.OMP.EXE/NyxParticles.o' failed
make: *** [tmp_build_dir/o/3d.gnu.MPI.OMP.EXE/NyxParticles.o] Error 1

**Comment by zingale** [comment]
It seems that Nyx's `master` branch has not been updated in some time.  I see this failure there.  Try checking out `development` in Nyx:

```
git checkout development
```
and then 
```
make realclean
```
and try your build again.

**Comment by disheng222** [comment]
Hi, 
It works now. 
Thanks!

Best,
Sheng
