### ISSUE TITLE
mhd_enforce_minimum_density_3d does not include magnetic field

### ISSUE THREAD

**Issue by zingale** [BoxLib-Codes/Nyx#31]
If the state is reset in `mhd_enforce_minimum_density_3d.F90`, the energy is recomputed:
```
uout(i,j,k,UEDEN) = uout(i,j,k,UEINT) + 0.5d0 / uout(i,j,k,URHO) * & 
                    ( uout(i,j,k,UMX)**2 + uout(i,j,k,UMY)**2 + uout(i,j,k,UMZ)**2 )
```
but this does not include the magnetic energy

**Comment by ghost** [comment]
Changed mhd_enforce_minimum_density_3d.F90 to actually enforce the density in a MHD way.
