### ISSUE TITLE
Sign issue in hlld.f90 in MHD

### ISSUE THREAD

**Issue by guadabsb15** [BoxLib-Codes/Nyx#35]
It looks like there might be a sign problem in line 106 and 107 of hlld.f90 in the magnetic components of F(U). The terms on the expression seem to have the sign swapped which according to the paper:
 u_D-1 * B_d  -  B_D-1 *u_d

**Comment by ghost** [comment]
It looks like it has been propagated throughout the magnetic flux terms within HLLD. I'll get to work on fixing them.

**Comment by ghost** [comment]
Changed, it to the proper fluxes. I'll look for other flux discrepancies in the rest of code.
