### ISSUE TITLE
AGN compilation problem

### ISSUE THREAD

**Issue by ctian282** [BoxLib-Codes/Nyx#40]
Hi,

When I was trying to run some AGN tests under LyA_AGN, I got few errors when compiling. 

First, It does not compile without Beeber but I do not know where to find it, so I turned it off. I will be appreciate if you can put the link to Beeber somewhere on the Nyx page.

Then, it reported error in Nyx_halos, where all calls to fillNeighbors(level) and clearNeighbors(level) do not match to the original function in AMReX_NeighborParticlesI.H, which have 0 argument. I tried to get rid of those arguments and then it compiles this file.

It also tells that all calls to neighbors[index]  in AGNParticleContainer.cpp have error since they are vectors of std pairs, not std pairs. I fixed this by changing them to neighbors[lev][index]. Then it compiles all through.

I just wonder is there anything unsafe for my change? And those compilation problems are result from the old version or they are just not recommended to be used?

**Comment by atmyers** [comment]
This is due to an upstream change in amrex. Your fix is correct. The fillNeighbor functions are safe to use, but it's been a while since anyone has used the AGN stuff, I believe, so you may run into other issues like this.

**Comment by ctian282** [comment]
Thanks for your replying. 

Can I run it without Reeber? If not, where can I find this package?
