### ISSUE TITLE
type errors

### ISSUE THREAD

**Issue by WeiqunZhang** [BoxLib-Codes/Nyx#6]
found by `make typecheck` in Exec/GravityTests/MacLaurin

Function tag_overdensity in Nyx_error_F.H vs. Fortran procedure in Tagging_3d.f90
    number of arguments 24 does NOT match 22.
    arg #20: C type ['int', 'pointer'] does NOT match Fortran type ('REAL 8', 'pointer', 'delta').

Function tag_region in Nyx_error_F.H vs. Fortran procedure in Tagging_3d.f90
    number of arguments 16 does NOT match 26.
    arg #10: C type ['int', 'pointer'] does NOT match Fortran type ('REAL 8', 'pointer', 'var').
    arg #13: C type ['double', 'pointer'] does NOT match Fortran type ('INTEGER 4', 'pointer', 'varl3').
    arg #14: C type ['double', 'pointer'] does NOT match Fortran type ('INTEGER 4', 'pointer', 'varh1').
    arg #15: C type ['double', 'pointer'] does NOT match Fortran type ('INTEGER 4', 'pointer', 'varh2').

Function integrate_state in Nyx_F.H vs. Fortran procedure in heat_cool_stubs.f90
    number of arguments 20 does NOT match 12.
    arg #11: C type ['int', 'pointer'] does NOT match Fortran type ('REAL 8', 'pointer', 'a').
    arg #12: C type ['int', 'pointer'] does NOT match Fortran type ('REAL 8', 'pointer', 'half_dt').

**Comment by WeiqunZhang** [comment]
The error in heat_cool_stubs.f90 is also in other tests.

**Comment by zarija** [comment]
Fixed.
