### ISSUE TITLE
HDF5 write error

### ISSUE THREAD

**Issue by prashplus** [BoxLib-Codes/Nyx#71]
I am trying to enable HDF5 output with AMReX_HDF5=YES option in compilation
and 1 extra line in inputs files
nyx.write_hdf5         = 0 

but getting this error : 

> `Gravity ... defining average density in Gravity::set_mass_offset to be 6.921051219e+10
> Gravity ... multilevel solve for new phi at base level 0 to finest level 0
>  ... subtracting average density 6.921051219e+10 from RHS at each level 
>  ... subtracting -1.985579729e-06 to ensure solvability 
> Average     gas density 6921051219
> Average       dm density 6.228946097e+10
> Average    total density 6.921051219e+10
> Average temperature 1923.146861
> ... setting small_dens to 6921.051105
> ... setting small_temp to 0.001
> ... setting small_pres to 0.09710685272
> INITIAL GRIDS 
>   Level 0   1 grids  32768 cells  100 % of domain
> 
> CHECKPOINT: file = chk00000
> checkPoint() time = 0.004195693 secs.
> PLOTFILE: file = plt00000
> Skip writePlotFilePre
> malloc(): corrupted top size
> `

**Comment by houjun** [comment]
Hi @prashplus , I implemented the HDF5 I/O in AMReX, could you please provide some more information on how you got the error, such as what system you used, how you configured AMReX and Nyx, the input files you used, etc., so we can try to reproduce the error and figure out what went wrong.

**Comment by prashplus** [comment]
Just cloned AMReX and Nyx using git.
using latest MPICH and OpenMP
Set env variable by export AMREX_HOME=/path/to/amrex/
My laptop specs : 
OS : Manjaro Arch, CPU - i7-9750H
Nyx is working normally if I dont do anything realted to HDF5.

**I. First way (GNUMake)**
1. cd Nyx/Exec/MiniSB
2. added one line in GNUMakefile  ----- USE_HDF5=TRUE
3. compiled using make -j6 command                                   
4. it gave me errors like this


> In file included from /home/prashant/astro/amrex/Src/Particle/AMReX_Particles.H:1350,
>                  from /home/prashant/astro/amrex/Src/Particle/AMReX_NeighborParticles.H:7,
>                  from ../../Source/Particle/NyxParticleContainer.H:6,
>                  from ../../Source/Driver/Nyx.H:11,
>                  from Prob_error.cpp:1:
> /home/prashant/astro/amrex/Src/Particle/AMReX_ParticleHDF5.H:19:58: error: invalid use of incomplete type ‘class amrex::ParticleContainer<NStructReal, NStructInt, NArrayReal, NArrayInt>’
>    19 |               const Vector<std::string>& int_comp_names) const
>       |                                                          ^~~~~
> In file included from /home/prashant/astro/amrex/Src/Particle/AMReX_NeighborParticles.H:7,
>                  from ../../Source/Particle/NyxParticleContainer.H:6,
>                  from ../../Source/Driver/Nyx.H:11,
>                  from Prob_error.cpp:1:

some more .....

> /home/prashant/astro/amrex/Src/Particle/AMReX_ParticleHDF5.H:902:63: error: invalid use of incomplete type ‘class amrex::ParticleContainer<NStructReal, NStructInt, NArrayReal, NArrayInt>’
>   902 | ::RestartHDF5 (const std::string& dir, const std::string& file)
>       |                                                               ^
> In file included from /home/prashant/astro/amrex/Src/Particle/AMReX_NeighborParticles.H:7,
>                  from ../../Source/Particle/NyxParticleContainer.H:6,
>                  from ../../Source/Driver/Nyx.H:11,
>                  from Prob_error.cpp:1:

some more .....

> make: *** [/home/prashant/astro/amrex/Tools/GNUMake/Make.rules:193: tmp_build_dir/o/3d.gnu.MPI.EXE/Prob.o] Error 1
> make: *** Waiting for unfinished jobs....
> make: *** [/home/prashant/astro/amrex/Tools/GNUMake/Make.rules:193: tmp_build_dir/o/3d.gnu.MPI.EXE/Prob_error.o] Error 1
> make: *** [/home/prashant/astro/amrex/Tools/GNUMake/Make.rules:193: tmp_build_dir/o/3d.gnu.MPI.EXE/nyx_main.o] Error 1
> make: *** [/home/prashant/astro/amrex/Tools/GNUMake/Make.rules:193: tmp_build_dir/o/3d.gnu.MPI.EXE/NyxBld.o] Error 1
> make: *** [/home/prashant/astro/amrex/Tools/GNUMake/Make.rules:193: tmp_build_dir/o/3d.gnu.MPI.EXE/comoving.o] Error 1
> make: *** [/home/prashant/astro/amrex/Tools/GNUMake/Make.rules:193: tmp_build_dir/o/3d.gnu.MPI.EXE/Nyx.o] Error 1

**II. Second way (cmake)**
1. created a nyx-build directory
2. ran cmake command with following options
`cmake \
-DCMAKE_C_COMPILER=$(which cc)  \
-DCMAKE_CXX_COMPILER=$(which CC)   \
-DCMAKE_CXX_STANDARD=17 \
-DBUILD_SHARED_LIBS=yes \
-DNyx_MPI=yes \
-DNyx_MPI_THREAD_MULTIPLE=yes \
-DNyx_OMP=yes \
-DNyx_HYDRO=yes \
-DNyx_HEATCOOL=yes \
-DAMReX_OMP=YES \
-DAMReX_PARTICLES=YES \
-DAMReX_MPI_THREAD_MULTIPLE=YES \
-DAMReX_HDF5=YES \
-DAMReX_PLOTFILE_TOOLS=YES \
-DCMAKE_BUILD_TYPE=Release \
/home/prashant/astro/Nyx
`
3. cd Nyx/Exec/MiniSB
4. compiled using make command 
6. added 2 lines in inputs.32 file ----- nyx.write_hdf5  = 1 
                                                   ----- nyx.heat_cool_type   = 11
_// as I got hint from the inputs.cuda_

7. It gave me this error : 

> Gravity ... defining average density in Gravity::set_mass_offset to be 6.921051219e+10
> Gravity ... multilevel solve for new phi at base level 0 to finest level 0
>  ... subtracting average density 6.921051219e+10 from RHS at each level 
>  ... subtracting -2.00048089e-06 to ensure solvability 
> Average     gas density 6921051219
> Average       dm density 6.228946097e+10
> Average    total density 6.921051219e+10
> Average temperature 1923.146861
> ... setting small_dens to 6921.051105
> ... setting small_temp to 0.001
> ... setting small_pres to 0.09710685272
> INITIAL GRIDS 
>   Level 0   1 grids  32768 cells  100 % of domain
> 
> CHECKPOINT: file = chk00000
> checkPoint() time = 0.008897287 secs.
> PLOTFILE: file = plt00000
> Skip writePlotFilePre
> malloc(): corrupted top size
> SIGABRT

**Comment by houjun** [comment]
@prashplus The compile error is fixed with a merged pull request from AMReX https://github.com/AMReX-Codes/amrex/pull/1777
I'm able to reproduce the error when nyx.write_hdf5 is specified in the input file, it appears to be from Nyx/Source/IO/Nyx_output.cpp:249  const auto& derive_dat = derive(it->name(), cur_time, nGrow); Going to look more into it with Nyx developers.

**Comment by mic84** [comment]
@prashplus please note that the amrex options such as `AMReX_OMP` are overshadowed by their Nyx counterpart, i.e. `Nyx_OMP`, so there is no need to pass both. The correct invocation for your case is: 

`cmake \ -DCMAKE_C_COMPILER=$(which cc) \ -DCMAKE_CXX_COMPILER=$(which CC) \ -DCMAKE_CXX_STANDARD=17 \ -DBUILD_SHARED_LIBS=yes \ -DNyx_MPI=yes \ -DNyx_MPI_THREAD_MULTIPLE=yes \ -DNyx_OMP=yes \ -DNyx_HYDRO=yes \ -DNyx_HEATCOOL=yes \ -DAMReX_HDF5=YES \ -DAMReX_PLOTFILE_TOOLS=YES \ -DCMAKE_BUILD_TYPE=Release \ /home/prashant/astro/Nyx`

Note that the only amrex options used are those that don't have a Nyx equivalent.

**Comment by prashplus** [comment]
Oh, Thanks guys. @mic84 @houjun

**Comment by prashplus** [comment]
**I was trying to run Plot2HDF5_grids converter and came accross this error.**

> (base) [prashant@helios Plotfile2HDF5_grids]$ mpirun -np 2 ./convert3d.gnu.PROF.MPI.ex input_path=plt00302 output_path=.
> MPI initialized with 2 MPI processes
> MPI initialized with thread support level 0
> AMReX (21.03-22-g9b17f925887a) initialized
> 
> amrex::Abort::1::bad state name in AmrData::StateNumber() !!!
> SIGABRT
> Error:  bad state name:  particle_x_velocity
> amrex::Abort::0::bad state name in AmrData::StateNumber() !!!
> SIGABRT
> Opening plt00302 ... done.
> Parameters:  Om = 0.275;  Ob = 0.046;  h_0 = 0.702;  L = 20
> Neutrinos are off
> 
> Hydro on
> Converting (dm) particle quantities 
>    particle mass density 
> See Backtrace.0 file for details
> See Backtrace.1 file for details
> --------------------------------------------------------------------------
> MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
> with errorcode 6.
> 
> NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
> You may or may not see output from other processes, depending on
> exactly when Open MPI kills them.
> --------------------------------------------------------------------------
> [helios:76817] 1 more process has sent help message help-mpi-api.txt / mpi-abort
> [helios:76817] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

Here is one of the Backtrace file...

> === If no file names and line numbers are shown below, one can run
>             addr2line -Cpfie my_exefile my_line_address
>     to convert `my_line_address` (e.g., 0x4a6b) into file name and line number.
>     Or one can use amrex/Tools/Backtrace/parse_bt.py.
> 
> === Please note that the line number reported by addr2line may not be accurate.
>     One can use
>             readelf -wl my_exefile | grep my_line_address'
>     to find out the offset for that line.
> 
>  0: ./convert3d.gnu.PROF.MPI.ex(+0x16fff1) [0x56151ef45ff1]
>     amrex::BLBackTrace::print_backtrace_info(_IO_FILE*)
> /home/prashant/thesis/astro/amrex/Src/Base/AMReX_BLBackTrace.cpp:179:39
> 
>  1: ./convert3d.gnu.PROF.MPI.ex(+0x1722b2) [0x56151ef482b2]
>     amrex::BLBackTrace::handler(int)
> /home/prashant/thesis/astro/amrex/Src/Base/AMReX_BLBackTrace.cpp:85:8
> 
>  2: ./convert3d.gnu.PROF.MPI.ex(+0x184b0c) [0x56151ef5ab0c]
>     amrex::AmrData::StateNumber(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const inlined at /home/prashant/thesis/astro/amrex/Src/Extern/amrdata/AMReX_AmrData.cpp:1949:5 in amrex::AmrData::StateNumber(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
> /home/prashant/thesis/astro/amrex/Src/Extern/amrdata/AMReX_AmrData.cpp:1959:3
> amrex::AmrData::StateNumber(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
> /home/prashant/thesis/astro/amrex/Src/Extern/amrdata/AMReX_AmrData.cpp:1949:5
> 
>  3: ./convert3d.gnu.PROF.MPI.ex(+0x1eb21) [0x56151edf4b21]
>     std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_data() const inlined at /usr/include/c++/10.2.0/bits/basic_string.h:222:23 in main
> /usr/include/c++/10.2.0/bits/basic_string.h:187:28
> std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_is_local() const
> /usr/include/c++/10.2.0/bits/basic_string.h:222:23
> std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose()
> /usr/include/c++/10.2.0/bits/basic_string.h:231:18
> std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
> /usr/include/c++/10.2.0/bits/basic_string.h:658:19
> main
> /home/prashant/thesis/astro/Nyx/Util/Converters/Plotfile2HDF5_grids/AmrDerive.cpp:559:58
> 
>  4: /usr/lib/libc.so.6(__libc_start_main+0xd5) [0x7f6b3c016b25]
>     __libc_start_main
> ??:0
> 
>  5: ./convert3d.gnu.PROF.MPI.ex(+0x2556e) [0x56151edfb56e]
>     _start
> ??:0
> 


I was going to reuse this converter's code for some other purpose. Can you help me out?
