### ISSUE TITLE
JOSS Review: Statement of Need

### ISSUE THREAD

**Issue by c-white** [BoxLib-Codes/Nyx#76]
I am one of the reviewers for the [JOSS submission](https://github.com/openjournals/joss-reviews/issues/3068). Everything looks great so far, though I have a tiny suggestion regarding the statement of need. It could be a bit more specific about:

1. "What problems the software is designed to solve" (though I understand that's mentioned elsewhere in the paper).
2. More importantly, "who the target audience is." For example, the code seems aimed at researchers with access to at least some HPC resources (as opposed to, say, students taking their first cosmology class).

**Comment by jmsexton03** [comment]
Thank you for being a reviewer. 

I've pushed an update to development which I believe makes the "Statement of Need" more specific and may address this issue.

**Comment by c-white** [comment]
I see two updates today, both of which look good. The latter seems to overwrite the former, whether or not this was intentional.
