### ISSUE TITLE
MiniSB example, use of amrex

### ISSUE THREAD

**Issue by teuben** [BoxLib-Codes/Nyx#78]
I guess the easiest path (which is in the docs) is to git clone with the --recursive flag.
However the default in the GNUMakefile for the MiniSB example is not what this method gives:
         AMREX_HOME ?= ../../../amrex
it would seem
          AMREX_HOME ?= ../../subprojects/amrex/
makes more sense as a default.

**Comment by asalmgren** [comment]
Thank you for pointing this out -- this has been updated in all the GNUmakefiles.
