### ISSUE TITLE
make vs. cmake

### ISSUE THREAD

**Issue by teuben** [BoxLib-Codes/Nyx#79]
I applaud you for keeping both install methods working.  It confused me though, to read the install directions for "make" that I needed to set the COMP to something like gnu or intel.....   instead of using the CXX/CC name standards?   In my case, what would one do if the compile is called g++-10. 

(i know, i can track this down by following the include hiaerarchy.... which also make me realize the only Linux is supported? Has a  MacOSX been tried?   Might be useful to make a note of this somewhere, to prevent frustrations?

**Comment by WeiqunZhang** [comment]
https://amrex-codes.github.io/amrex/docs_html/BuildingAMReX.html#gcc-on-macos

**Comment by teuben** [comment]
on the MacOSX I had a comment on this in #80

**Comment by jmsexton03** [comment]
Added reference to amrex documentaiton in [Nyx build documentation](https://amrex-astro.github.io/Nyx/docs_html/NyxGettingStarted.html)
Added CI for CMake macos build
