### ISSUE TITLE
some paper.md comments

### ISSUE THREAD

**Issue by teuben** [BoxLib-Codes/Nyx#80]
A few comments on the paper:

- Strang splitting :   maybe a  reference here ?  It's not my field, but I've not heard of this.
- six species:    I counted five
- "using geometric" -> "using the/a geometric" ?  (an article seems to be missing,
  but is it "the" or one of many ("a") ?
- "is necessity"  -> "is a necessity", i believe an article is missing
- "we do best effort" -> "we made a best effort" ( think,  I'm not a native speaker though)
- there ought to be a comment for poor MacOSX users here, since Linux is mentioned. Should they not bother?

From https://github.com/openjournals/joss-reviews/issues/3068

**Comment by zarija** [comment]
- Added a reference for Strang splitting.
- Six species are: neutral and ionized hydrogen, neutral, once and twice ionized helium, and free electrons.
- Made suggested grammar changes; if a native speaker can additionally go through it and fix other a/the articles that would be great.
- Added a brief comment about Macs...  Basically, it boils down to the fact that Nyx is really a high-performance computing (HPC) code, and there's no HPC platform running iOS.  Thus while Mac can be a convenient tool for Nyx code development, meaningful simulations cannot really be produced on Macs.

**Comment by jmsexton03** [comment]
I went through and polished up the grammar.
